version: "3"

services:
  logstash:
    build: .
    image: dsolab/passets-logstash:1.0.0
    container_name: passets-logstash
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_URL=<elasticsearch-host>:9200
      - ELASTICSEARCH_INDEX=logstash-passets
      - INNER_IP_LIST=10.0.0.0-10.255.255.255,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,169.254.0.0-169.254.255.255,127.0.0.1-127.0.0.255
    ports:
      - "5044:5044/udp"

